###
GET https://discourse.tbp.land/categories
Accept: application/json
Api-Key: {{api-key}}
Api-Username: {{api-username}}

###
GET https://discourse.tbp.land/tags
Accept: application/json
Api-Key: {{api-key}}
Api-Username: {{api-username}}

###
GET https://discourse.tbp.land/c/a-shadow-of-the-day/206
Accept: application/json
Api-Key: {{api-key}}
Api-Username: {{api-username}}


###
GET https://discourse.tbp.land/t/4339
Accept: application/json
Api-Key: {{api-key}}
Api-Username: {{api-username}}



###
GET https://discourse.tbp.land/posts/5452
Accept: application/json
Api-Key: {{api-key}}
Api-Username: {{api-username}}
